package com.simba.snip.npo.integration.sync;

public enum KnowledgeConfidenceReason {
    NO_TRUSTED_BASELINE,
    TRUSTED_FRESH_COMPLETE,
    AGING_TRUSTED_STATE,
    STALE_TRUSTED_STATE,
    RECENT_OPERATIONAL_FAILURE,
    RECOVERY_REQUIRED,
    CHECKPOINT_UNCERTAIN,
    PARTIAL_SNAPSHOT,
    SOURCE_DEGRADED,
    SOURCE_UNREACHABLE,
    INCREMENTAL_FAILURE_WITH_VALID_BASELINE
}
