package com.simba.snip.npo.integration;

public enum ImportAuditEventType {
    IMPORT_STARTED,
    SNAPSHOT_READ,
    VALIDATION_COMPLETED,
    RECONCILIATION_COMPLETED,
    IMPORT_COMPLETED,
    IMPORT_FAILED,
    IMPORT_REJECTED,
    IMPORT_REPLAYED,
    IMPORT_TIMED_OUT,
    LEASE_ACQUIRED,
    LEASE_RELEASED
}
