package com.simba.snip.npo.integration;

public enum ImportFailureCode {
    ADAPTER_ERROR,
    SNAPSHOT_READ_FAILED,
    SCHEMA_UNSUPPORTED,
    VALIDATION_FATAL,
    LEASE_UNAVAILABLE,
    LEASE_LOST,
    LEASE_EXPIRED,
    EXECUTION_TIMEOUT,
    RECONCILIATION_FAILED,
    DATABASE_COMMIT_FAILED,
    SNAPSHOT_ID_CONTENT_MISMATCH
}
