package com.simba.snip.npo.productioncampaign.domain;

public enum CampaignPermission {
    CAMPAIGN_VIEW,
    CAMPAIGN_CREATE,
    CAMPAIGN_REVIEW,
    CAMPAIGN_AUTHORIZE,
    RELEASE_COHORT,
    CAMPAIGN_PAUSE,
    CAMPAIGN_ABORT,
    VIEW_CAMPAIGN_EVIDENCE,
    CAMPAIGN_RESUMPTION_REVIEW,
    CAMPAIGN_RESUMPTION_AUTHORIZE,
    CAMPAIGN_RECOVERY_REQUEST,
    CAMPAIGN_RECOVERY_REVIEW,
    CAMPAIGN_RECOVERY_AUTHORIZE
}
