package com.simba.snip.npo.productionchange.protocol;

public enum ProductionChangeStatus {
    REQUESTED,
    ADMISSION_REJECTED,
    READY_FOR_REVIEW,
    REVIEWED,
    REVIEW_REJECTED,
    AUTHORIZED,
    AUTHORIZATION_STALE,
    PREFLIGHT_DENIED,
    EXECUTE_DENIED,
    CONSUMED_PRE_SEND_RECOVERY_REQUIRED,
    OUTCOME_UNKNOWN,
    VERIFYING,
    VERIFIED,
    VERIFICATION_FAILED,
    RECOVERY_REQUIRED,
    MANUAL_INTERVENTION_REQUIRED,
    PRODUCTION_OUTCOME_UNRESOLVED,
    NETWORK_SYNCHRONIZATION_REQUIRED,
    ROLLBACK_REQUESTED,
    ROLLBACK_REVIEWED,
    ROLLBACK_AUTHORIZED,
    ROLLED_BACK,
    ROLLBACK_OUTCOME_UNKNOWN,
    CANCELLED_BEFORE_MUTATION
}
