package com.simba.snip.npo.changeintelligence.model;

public enum ChangeProposalFailureCode {
    UNSUPPORTED_PARAMETER,
    UNSUPPORTED_TARGET,
    NETWORK_KNOWLEDGE_LOW,
    NETWORK_KNOWLEDGE_UNKNOWN,
    CURRENT_STATE_UNAVAILABLE,
    CANDIDATE_OUT_OF_RANGE,
    NO_VALID_CANDIDATES,
    TWIN_STATE_UNAVAILABLE,
    TWIN_STATE_STALE,
    SIMULATION_FAILED,
    NO_BENEFICIAL_CANDIDATE,
    PROPOSAL_EXPIRED,
    PROPOSAL_INVALIDATED,
    PROPOSAL_SUPERSEDED,
    CURRENT_VALUE_CHANGED,
    KNOWLEDGE_CONFIDENCE_DEGRADED,
    INVALID_PROPOSAL_STATE,
    PROPOSAL_GENERATION_FORBIDDEN,
    PROPOSAL_REVIEW_FORBIDDEN,
    PROPOSAL_APPROVAL_FORBIDDEN,
    PROPOSAL_REJECTION_FORBIDDEN,
    CONCURRENT_REVIEW_CONFLICT
}
