package com.simba.snip.npo.planning;

public enum PlanningFailureCode {
    SCENARIO_NOT_FOUND,
    EVALUATION_NOT_FOUND,
    CELL_UNKNOWN,
    CELL_NOT_IN_SCENARIO,
    UNSUPPORTED_PARAMETER,
    PARAMETER_OUT_OF_RANGE,
    BOUNDS_EXCEEDED,
    SCENARIO_VERSION_CONFLICT,
    EVALUATION_IN_PROGRESS,
    EMPTY_INTENTS,
    ADMISSION_TWIN_MISSING,
    ADMISSION_TWIN_NOT_CURRENT,
    ADMISSION_BASELINE_MISSING,
    SIMULATION_REJECTED,
    SIMULATION_FAILED
}
