package com.simba.snip.npo.productionwritegateway.service;

public enum FailureInjectionPoint {
    BEFORE_GRANT_LOOKUP,
    BEFORE_CONSUME,
    AFTER_CONSUME_BEFORE_ATTEMPT,
    AFTER_ATTEMPT_BEFORE_PREFLIGHT,
    BEFORE_CREDENTIAL,
    BEFORE_OBSERVATION,
    BEFORE_MUTATION,
    MUTATION_INVOKE_START,
    VENDOR_APPLIED_RESPONSE_LOST,
    BEFORE_VERIFICATION,
    AFTER_VERIFICATION_BEFORE_PERSIST,
    VERIFICATION_PERSIST_FAIL,
    RB_BEFORE_GRANT_LOOKUP,
    RB_BEFORE_CONSUME,
    RB_AFTER_CONSUME_BEFORE_ATTEMPT,
    RB_AFTER_ATTEMPT_BEFORE_PREFLIGHT,
    RB_BEFORE_CREDENTIAL,
    RB_BEFORE_OBSERVATION,
    RB_BEFORE_MUTATION,
    RB_MUTATION_INVOKE_START,
    RB_VENDOR_APPLIED_RESPONSE_LOST
}
