package com.simba.snip.npo.changeplanning.model;

public enum PreconditionType {
    EXPECTED_PARAMETER_VALUE,
    NETWORK_KNOWLEDGE_CONFIDENCE,
    SOURCE_SYNCHRONIZATION_FRESHNESS,
    NO_RELEVANT_DRIFT,
    TWIN_COMPATIBILITY,
    PROPOSAL_STILL_VALID,
    TARGET_EXISTS,
    ROLLBACK_AVAILABLE,
    DEPENDENCY_GRAPH_VALID,
    FINGERPRINT_CURRENT,
    AUTHORIZATION_CURRENT
}
