package com.simba.snip.npo.changeintelligence.model;

public enum ChangeProposalAuditEventType {
    PROPOSAL_GENERATION_REQUESTED,
    PROPOSAL_GENERATION_BLOCKED,
    PROPOSAL_GENERATED,
    PROPOSAL_EVALUATED,
    RECOMMENDATION_PRODUCED,
    PROPOSAL_INVALIDATED,
    PROPOSAL_EXPIRED,
    PROPOSAL_SUPERSEDED,
    APPROVAL_ATTEMPTED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED
}
