package com.simba.snip.npo.integration;

public enum RejectionReasonCode {
    MISSING_SOURCE_ID,
    MISSING_CANONICAL_ID,
    DUPLICATE_SOURCE_IDENTITY,
    UNSUPPORTED_TECHNOLOGY,
    UNSUPPORTED_DUPLEX,
    INVALID_UNIT,
    INVALID_TX_POWER,
    MISSING_PARENT,
    INVALID_NEIGHBOUR,
    MALFORMED_RELATIONSHIP
}
