package com.simba.snip.npo.action;

public enum AuditEventType {
    ACTION_PROPOSED,
    POLICY_EVALUATED,
    APPROVAL_REQUESTED,
    ACTION_APPROVED,
    ACTION_REJECTED,
    ACTION_DENIED,
    MCP_INVOCATION_STARTED,
    MCP_INVOCATION_SUCCEEDED,
    MCP_INVOCATION_FAILED
}
